version: "3.8"

services:
  db:
    image: postgres:12-alpine
    container_name: authen_db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: authen
      POSTGRES_PASSWORD: "123456"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - authen
    restart: always
volumes:
  postgres:

networks:
  authen:
    name: authen
    driver: bridge
